### ISSUE TITLE
Error importing screen from lagoon

### ISSUE THREAD

**Issue by aoxolotl** [combatopera/lagoon#6]
While running Concern I get an error: 
`ImportError: cannot import name 'screen' from 'lagoon'`
I could trace this to the file `screen.py` which has the line
```from lagoon import screen```
But there is no module called screen inside the lagoon folder. Is this because of a version conflict or missing dependencies?
Thanks!

**Comment by combatopera** [comment]
Hi @aoxolotl,

lagoon is a library for importing programs by name as if they were functions. In this case it's looking for GNU Screen, which can't be bundled with Concern and must be installed separately. If you're on a Debian-based system you can do:

`sudo apt-get install screen`

**Comment by aoxolotl** [comment]
Awesome! That seems to work. Thanks @combatopera !

**Comment by aoxolotl** [comment]
Should we add this to the README? I think it will help while setting up

**Comment by combatopera** [comment]
Yes, definitely. If you're keen to make this change, would you like to raise a pull request? Otherwise I'm happy to do it.

**Comment by aoxolotl** [comment]
Cool. I'll take it up. Do you mind marking the PR as `hacktoberfest-accepted`? I am taking part in the [challenge](https://hacktoberfest.digitalocean.com)!

**Comment by combatopera** [comment]
awesome, i've added the label, and a review
